on: workflow_dispatch

name: Aikido Scan Dockerized
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: aikidosecurity/local-scanner:latest
    steps: 
      - uses: actions/checkout@v4 
        with: 
          token: ${{ secrets.GITHUB_TOKEN }} 
          path: demo-app
      - name: Run scan
        run: aikido-local-scanner scan demo-app --repositoryname demo-app --branchname main --apikey AIK_CI_X0oCFY7T9POOiTkewXJBRtxTF0J2e5vCIv1XISLPrj18CjCt00yvuiJv59OJAywt --gating-result-output output.json --fail-on low
      - name: ls
        run: ls
